set lines 150
set head on 
set echo on
set feed on
select name from v$database;
select to_char(sysdate,'DD-MON-YYYY HH24:MI:SS') from dual;
ALTER INDEX TCSDBOWNER.PKSPRSTATEHRS REBUILD;
ALTER INDEX TCSDBOWNER.IF2SPRSTATEHRS REBUILD;
ALTER INDEX TCSDBOWNER.IF2GRNTSTFGRP REBUILD;
ALTER INDEX TCSDBOWNER.IF3GRNTSEGCODE REBUILD;
ALTER INDEX TCSDBOWNER.AK1FSCFORASM REBUILD;
ALTER INDEX TCSDBOWNER.IF2GRNTSEGCODE REBUILD;
ALTER INDEX TCSDBOWNER.IF4GRNTSEGCODE REBUILD;
ALTER INDEX TCSDBOWNER.IE4AUDGRNTSTFGRP REBUILD;
ALTER INDEX TCSDBOWNER.IE2AUDTCSLOGIN REBUILD;
ALTER INDEX TCSDBOWNER.IF1AUDTCSLOGIN REBUILD;
ALTER INDEX TCSDBOWNER.PKACDCALLGRPSTAT REBUILD;
ALTER INDEX TCSDBOWNER.IE3AUDGRNTFORGRP REBUILD;
ALTER INDEX TCSDBOWNER.PKRQSMEMO REBUILD;
ALTER INDEX TCSDBOWNER.IF1EXTRAEMPFIELD REBUILD;
ALTER INDEX TCSDBOWNER.IE2AUDSECURPROF REBUILD;
ALTER INDEX TCSDBOWNER.PKIDPAGNPRFC REBUILD;
ALTER INDEX TCSDBOWNER.IE2AUDGRNTSEGCODE REBUILD;
ALTER INDEX TCSDBOWNER.IE1APRAWSTAT REBUILD;
ALTER INDEX TCSDBOWNER.PKSTFOVRDDET REBUILD;
ALTER INDEX TCSDBOWNER.AK1EMPGRPASS REBUILD;
ALTER INDEX TCSDBOWNER.IF2RQSHSTCELL REBUILD;
ALTER INDEX TCSDBOWNER.AK1EMPSCHPREFASM REBUILD;
ALTER INDEX TCSDBOWNER.IE1ACDRAWSTAT REBUILD;
ALTER INDEX TCSDBOWNER.IE2AUDGRNTFORGRP REBUILD;
ALTER INDEX TCSDBOWNER.AK1TRLSCH REBUILD;
ALTER INDEX TCSDBOWNER.IF1AUDGRNTSEGCODE REBUILD;
ALTER INDEX TCSDBOWNER.IF1AUDSECURPROF REBUILD;
ALTER INDEX TCSDBOWNER.IE2AUDGRNTSTFGRP REBUILD;
ALTER INDEX TCSDBOWNER.PKGRNTSEGCODE REBUILD;
ALTER INDEX TCSDBOWNER.PKAHTOVRDDET REBUILD;
ALTER INDEX TCSDBOWNER.IF1AUDGRNTFORGRP REBUILD;
ALTER INDEX TCSDBOWNER.IF1AUDGRNTSTFGRP REBUILD;
select to_char(sysdate,'DD-MON-YYYY HH24:MI:SS') from dual;
exit;